Repository voxel51/api-js, pull requests merged in 2018-12, with the labels that each got.

#17 Date interface name changes
  lib/query.js
Labels: cleaning, documentation

#18 Adds analytic id field to job query obj
  lib/query.js
Labels: documentation, feature

#19 Adding support for use_gpu option
  lib/api.js
  lib/query.js
Labels: feature
