Repository voxel51/api-js, pull requests merged in 2019-03, with the labels that each got.

#27 Adds new job query fields
  lib/query.js
Labels: feature

#28 Remove statements from API
  lib/api.js
  lib/apps/api.js
Labels: cleaning

#29 Adds platform user route to delete private analytic
  lib/api.js
Labels: feature

#30 Adds route for applications to upload/delete custom analytics
  lib/api.js
  lib/apps/api.js
Labels: feature

#31 Adds pending query field to analytics
  lib/query.js
Labels: enhancement

#32 Removing support_cpu/gpu flags from API methods
  lib/api.js
  lib/apps/api.js
Labels: enhancement

#33 Adds routes for job logfile stream/download url
  lib/api.js
Labels: feature

#34 Adding analytics routes for applications
  lib/apps/api.js
Labels: feature

#36 Adding autoBind to solve class binding problems
  lib/api.js
  lib/apps/api.js
  lib/apps/auth.js
  lib/auth.js
  lib/jobs.js
  lib/query.js
  lib/utils.js
  package-lock.json
  package.json
Labels: enhancement

#35 Small section draft for using Promise.all for "threaded" behavior
  README.md
Labels: documentation
