Repository voxel51/api-js, pull requests merged in 2019-12, with the labels that each got.

#58 Fix missing path module imports
  lib/apps/auth.js
  lib/users/auth.js
Labels: bug

#60 Add default output path to downloading job output
  lib/users/api.js
  lib/users/auth.js
  lib/users/utils.js
Labels: feature

#56 Add getAnalyticDetails route
  lib/apps/api.js
  lib/apps/auth.js
  lib/users/api.js
Labels: feature

#63 Make post data as url data ttl required
  lib/index.js
  lib/users/api.js
  lib/users/requests.js
Labels: enhancement

#61 Implement batch actions for data and jobs
  lib/users/api.js
Labels: feature

#59 Adding support for explicitly setting the expiration date when updating the TTL of data/jobs
  lib/users/api.js
Labels: feature

#64 Cleanup
  .eslintrc.js
  lib/apps/auth.js
  lib/users/api.js
  lib/users/auth.js
  lib/users/jobs.js
  lib/users/query.js
  lib/users/requests.js
  lib/users/utils.js
  package.json
Labels: bug, cleaning
