Repository voxel51/api-js, pull requests merged in 2020-01, with the labels that each got.

#68 Clarifying that expiration date is fixed when posting data as URL
  lib/users/api.js
Labels: documentation

#66 Moving applications docs to separate file
  APPLICATIONS.md
  README.md
  docs/generate_docs.bash
  docs/jsdoc.json
Labels: documentation

#70 Validate search fields client-side
  lib/users/query.js
Labels: bug

#71 Fix allVersions param of listAnalytics
  lib/users/api.js
  lib/users/utils.js
Labels: bug

#69 Rely on backend for batch error formatting
  lib/users/api.js
Labels: enhancement

#72 Adding support for setting token private key via environment variable
  APPLICATIONS.md
  README.md
  lib/apps/api.js
  lib/apps/auth.js
  lib/users/api.js
  lib/users/auth.js
Labels: feature

#75 Adding method to get analytic ID by name + version
  lib/users/api.js
  lib/users/query.js
Labels: feature
